name: Build-Test
on:
  pull_request:
    branches:
      - main


jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Pytest
        run: pip install pytest

      - name: Test with pytest
        run: python -m pytest -vv
