name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Pytest
        run: pip install pytest

      - name: Test with pytest
        run: python -m pytest -vv
